plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.4' // 안정적인 3.x 버전 권장
    id 'io.spring.dependency-management' version '1.1.4'
}

group = 'com.workspace'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}
dependencies {

    implementation 'org.springframework.boot:spring-boot-starter'
    // Web & Backend Core
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Google Cloud SDK (Speech & TTS)
    implementation 'com.google.cloud:google-cloud-speech:4.38.0'
    implementation 'com.google.cloud:google-cloud-texttospeech:2.42.0'

    // Database
    //runtimeOnly 'com.h2database:h2'
    runtimeOnly 'com.mysql:mysql-connector-j'

    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    runtimeOnly 'com.mysql:mysql-connector-j'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation 'com.github.codemonstur:embedded-redis:1.4.3'
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.3'

}


tasks.named('test') {
    useJUnitPlatform()
}

