plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.5'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.KoreaIT.ysh.demo'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
    // Web & Backend Core
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Audio Processing (External API SDKs - e.g., Google Cloud)
    implementation 'com.google.cloud:google-cloud-speech:4.38.0'
    implementation 'com.google.cloud:google-cloud-texttospeech:2.42.0'

    // Database & Monitoring
    runtimeOnly 'com.h2database:h2' // 초기 개발용
    implementation 'org.springframework.boot:spring-boot-starter-actuator' // 상태 모니터링

    implementation 'org.springframework.boot:spring-boot-starter-data-redis' //redis

    implementation 'org.springframework.boot:spring-boot-starter-websocket'


    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'org.springframework.boot:spring-boot-starter-json'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
}
tasks.named('test') {
	useJUnitPlatform()
}

